// client/src/components/chat-input.tsx
import {
  useEffect,
  useRef,
  useState,
  type ChangeEvent,
  type KeyboardEvent,
} from "react";

interface IProps {
  disabled: boolean;
  sendMessage: (message: string) => void;
  placeholder?: string;
}

export default function ChatInput(props: IProps) {
  const { disabled, placeholder = "请输入你的编程问题", sendMessage } = props;
  const [inputMessage, setInputMessage] = useState<string>("");

  const handleInput = (e: ChangeEvent<HTMLTextAreaElement>) => {
    setInputMessage(e.target.value);
  };

  const handleSendMessage = () => {
    if (inputMessage.trim() && !disabled) {
      sendMessage(inputMessage.trim());
      setInputMessage("");
      adjustHeight();
    }
  };

  const handleKeyDown = (e: KeyboardEvent<HTMLTextAreaElement>) => {
    // 正常输入也会触发 keydown 事件
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSendMessage();
    }
  };

  const textareaRef = useRef<HTMLTextAreaElement | null>(null);

  const adjustHeight = () => {
    requestAnimationFrame(() => {
      const textarea = textareaRef.current;
      if (textarea) {
        textarea.style.height = "auto";
        textarea.style.height = `${Math.min(textarea.scrollHeight, 200)}px`;
      }
    });
  };

  useEffect(() => {
    adjustHeight();
  }, []);

  const canSend = !disabled && inputMessage.trim();

  return (
    <div className="shadow-apple-lg focus-within:border-primary-300 focus-within:ring-primary-100 relative flex items-end gap-3 rounded-2xl border border-gray-200 bg-white p-3 transition-all duration-200 focus-within:ring-4">
      <textarea
        ref={textareaRef}
        value={inputMessage}
        onChange={handleInput}
        onInput={adjustHeight}
        disabled={disabled}
        rows={1}
        onKeyDown={handleKeyDown}
        placeholder={placeholder}
        className="scrollbar-thin max-h-[200px] flex-1 resize-none border-none bg-transparent text-sm leading-relaxed text-gray-700 placeholder-gray-400 outline-none"
      />
      <button
        disabled={!canSend}
        onClick={handleSendMessage}
        className={`flex h-10 w-10 flex-shrink-0 items-center justify-center rounded-xl transition-all duration-200 ease-out ${
          canSend
            ? "from-primary-500 to-primary-600 shadow-apple hover:shadow-apple-lg bg-gradient-to-br text-white hover:scale-105 active:scale-95"
            : "cursor-not-allowed bg-gray-100 text-gray-300"
        } `}
      >
        <svg
          className={`h-5 w-5 transition-transform duration-200 ${canSend ? "translate-x-0.5" : ""}`}
          fill="none"
          stroke="currentColor"
          viewBox="0 0 24 24"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth={2}
            d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8"
          />
        </svg>
      </button>
    </div>
  );
}

// ai-code-helper-frontend/src/components/ChatInput.vue
<template>
  <div class="chat-input">
    <div class="input-container">
      <textarea
        ref="inputRef"
        v-model="inputMessage"
        :placeholder="placeholder"
        :disabled="disabled"
        class="input-textarea"
        rows="1"
        @keydown="handleKeyDown"
        @input="adjustHeight"
      />
      <button
        :disabled="disabled || !inputMessage.trim()"
        @click="sendMessage"
        class="send-button"
      >
        <svg
          width="20"
          height="20"
          viewBox="0 0 24 24"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path d="M2 21l21-9L2 3v7l15 2-15 2v7z" fill="currentColor" />
        </svg>
      </button>
    </div>
  </div>
</template>

<script>
export default {
  name: "ChatInput",
  props: {
    disabled: {
      type: Boolean,
      default: false,
    },
    placeholder: {
      type: String,
      default: "请输入您的问题...",
    },
  },
  data() {
    return {
      inputMessage: "",
    };
  },
  methods: {
    sendMessage() {
      if (this.inputMessage.trim() && !this.disabled) {
        this.$emit("send-message", this.inputMessage.trim());
        this.inputMessage = "";
        this.adjustHeight();
      }
    },
    handleKeyDown(event) {
      if (event.key === "Enter" && !event.shiftKey) {
        event.preventDefault();
        this.sendMessage();
      }
    },
    adjustHeight() {
      this.$nextTick(() => {
        const textarea = this.$refs.inputRef;
        textarea.style.height = "auto";
        textarea.style.height = Math.min(textarea.scrollHeight, 120) + "px";
      });
    },
    focus() {
      this.$refs.inputRef.focus();
    },
  },
  mounted() {
    this.adjustHeight();
  },
};
</script>

<style scoped>
.chat-input {
  padding: 20px;
  background-color: white;
  border-top: 1px solid #e1e5e9;
}

.input-container {
  display: flex;
  align-items: flex-end;
  gap: 12px;
  max-width: 800px;
  margin: 0 auto;
}

.input-textarea {
  flex: 1;
  padding: 12px 16px;
  border: 1px solid #ddd;
  border-radius: 24px;
  font-size: 14px;
  line-height: 1.4;
  resize: none;
  outline: none;
  transition: border-color 0.2s;
  min-height: 44px;
  max-height: 120px;
  overflow-y: auto;
}

.input-textarea:focus {
  border-color: #007bff;
}

.input-textarea:disabled {
  background-color: #f5f5f5;
  color: #999;
  cursor: not-allowed;
}

.send-button {
  width: 44px;
  height: 44px;
  background-color: #007bff;
  border: none;
  border-radius: 50%;
  color: white;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: background-color 0.2s;
  flex-shrink: 0;
}

.send-button:hover:not(:disabled) {
  background-color: #0056b3;
}

.send-button:disabled {
  background-color: #ccc;
  cursor: not-allowed;
}

@media (max-width: 768px) {
  .chat-input {
    padding: 15px;
  }

  .input-container {
    gap: 8px;
  }

  .input-textarea {
    font-size: 16px; /* 防止在移动设备上自动缩放 */
  }
}
</style>
